.TH "NHibernate.CallbackException" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.CallbackException \- 
.PP
 

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.HibernateException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCallbackException\fP (Exception innerException)"
.br
.RI "\fIInitializes a new instance of the \fBCallbackException\fP class\&. \fP"
.ti -1c
.RI "\fBCallbackException\fP (string message)"
.br
.RI "\fIInitializes a new instance of the \fBCallbackException\fP class\&. \fP"
.ti -1c
.RI "\fBCallbackException\fP (string message, Exception innerException)"
.br
.RI "\fIInitializes a new instance of the \fBCallbackException\fP class\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBCallbackException\fP (SerializationInfo info, StreamingContext context)"
.br
.RI "\fIInitializes a new instance of the \fBCallbackException\fP class with serialized data\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 



.PP
Definition at line 8 of file CallbackException\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.CallbackException\&.CallbackException (ExceptioninnerException)"

.PP
Initializes a new instance of the \fBCallbackException\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinnerException\fP The exception that is the cause of the current exception\&. If the innerException parameter is not a null reference, the current exception is raised in a catch block that handles the inner exception\&. 
.RE
.PP

.PP
Definition at line 18 of file CallbackException\&.cs\&.
.SS "NHibernate\&.CallbackException\&.CallbackException (stringmessage)"

.PP
Initializes a new instance of the \fBCallbackException\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP The message that describes the error\&. 
.RE
.PP

.PP
Definition at line 26 of file CallbackException\&.cs\&.
.SS "NHibernate\&.CallbackException\&.CallbackException (stringmessage, ExceptioninnerException)"

.PP
Initializes a new instance of the \fBCallbackException\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP The message that describes the error\&. 
.br
\fIinnerException\fP The exception that is the cause of the current exception\&. If the innerException parameter is not a null reference, the current exception is raised in a catch block that handles the inner exception\&. 
.RE
.PP

.PP
Definition at line 39 of file CallbackException\&.cs\&.
.SS "NHibernate\&.CallbackException\&.CallbackException (SerializationInfoinfo, StreamingContextcontext)\fC [protected]\fP"

.PP
Initializes a new instance of the \fBCallbackException\fP class with serialized data\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinfo\fP The SerializationInfo that holds the serialized object data about the exception being thrown\&. 
.br
\fIcontext\fP The StreamingContext that contains contextual information about the source or destination\&. 
.RE
.PP

.PP
Definition at line 54 of file CallbackException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
